### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by liorbrauer** [derekprior/momentjs-rails#58]
Hi @derekprior, thanks for making this project! 

I wanted to know if this repo is still maintained? If not, I'll be happy to help maintain it. 
Meanwhile I'm making a fork to update `momentjs-rails` to the latest moment version (2.24.0).

Best,
Lior

**Comment by derekprior** [comment]
I have a couple of thoughts on this:

1. I generally bump the version when someone submits a PR to do so, though I have also long believed that this process of creating ruby gems from javascript packages is something we should stop doing. There are many better options, be it rails-assets.org or, on more recent Rails versions, webpacker.

2. I'm increasingly uncomfortable merging in pull requests from contributors because it puts me on the hook for reviewing the submitted files. It'd be trivial for someone to come along claiming that their PR updates to Moment 2.24.0 while also slipping in bitcoin mining or some other nefarious code. To date, that hasn't happened, but unless I do the work myself of getting and verifying the files directly from the moment distribution, I can't really have any assurances that the code as released by moment is replicated exactly by this gem.

So where does this leave me? I feel like maintaining this gem at all moving forward requires one of two things:

A. I do the work of updating the vendored code myself
B. We add an automated test that matches the vendored code to released code

I don't have time to do either myself right now, though I'd certainly be in a better spot to review B. What do you think?

**Comment by liorbrauer** [comment]
Valid points. I do agree that the fashion of wrapping javascript packages in ruby gems is quickly going out of style (with good reason and with good alternatives). 

I also understand your valid concern of verifying the integrity of PRs.

I'm curious to play around with writing an automated test that tries to match the vendored code to released code. I haven't used github actions yet but I assume this is something it can handle? I'll do some quick reading and let you know how it goes. 

Thanks for the thoughtful response!
